# get file provenances, recursive; here filtering for module "irirs_summary_metrics" ancestors

PREFIX omni: <http://omnibenchmark.org/ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?target_module_name ?target_kw ?recursive_module_name ?kw ?predecessor_module_name ?pre_fn ?post_fn

where {
  ?target_module a omni:Module ;
    omni:hasModuleName ?target_module_name ;	
  	omni:hasKeyword ?target_kw .
  ?recursive_module a omni:Module ;
        omni:hasModuleName ?recursive_module_name ;	
  	omni:hasInputKeyword ?kw .
  ?predecessor_module a omni:Module ;
   omni:hasModuleName ?predecessor_module_name ;
  	omni:hasKeyword+ ?kw .

  ?d_pre a omni:Deliverable ;
                 omni:hasModuleName ?predecessor_module_name;
                 omni:hasInputPath ?pre_fn ;
                 omni:hasFileName ?post_fn .
    
  filter (?target_module_name = "irirs_summary_metrics"^^xsd:string )
}